dist: bionic
language: generic
sudo: required

addons:
  apt:
    sources:
    - sourceline: 'ppa:tah83/secp256k1'
    - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - build-essential
    - pkg-config
    - zlib1g-dev
    - libssl-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-test-dev
    - libjsoncpp-dev
    - libsecp256k1-dev
    - llvm-10-dev
cache:
  directories:
  - $HOME/openssl
branches:
  only:
    - master
    - /^release-v.*$/
script:
    - scripts/build_ci.sh
