name: CI

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install LLVM repositories Ubuntu
        if: runner.os == 'Linux'
        run: sudo add-apt-repository -y 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main'

      - name: Install required Ubuntu packages
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -yq build-essential pkg-config zlib1g-dev libssl-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-test-dev libjsoncpp-dev libsecp256k1-dev clang-12

      - name: Install required MacOS packages
        if: runner.os == 'macOS'
        run: brew update && brew upgrade && brew install llvm cmake openssl pkg-config boost autoconf automake libtool jsoncpp 

      - name: ScillaRTL Testsuite Release Build
        run: scripts/build_ci.sh
        env: 
          if: runner.os == 'macOS'
          OPENSSL_ROOT_DIR: '/usr/local/opt/openssl'
          LIBRARY_PATH: '/usr/local/opt/jsoncpp/lib:/usr/local/opt/secp256k1/lib/'

      - name: ScillaRTL Testsuite Debug Build
        run: scripts/dbuild_ci.sh
